import { eContractid, IReserveParams } from '../../helpers/types';

import {
  rateStrategyVolatileOne,
  rateStrategyStableOne,
  rateStrategyStableTwo,
  rateStrategyWETH,
  rateStrategyWstETH,
  rateStrategyHOPE,
  rateStrategyStakingHOPE,
  rateStrategyUSDT,
  rateStrategyWBTC,
  rateStrategyUSDC,
} from './rateStrategies';

export const strategyDAI: IReserveParams = {
  strategy: rateStrategyStableTwo,
  baseLTVAsCollateral: '7500',
  liquidationThreshold: '8000',
  liquidationBonus: '10500',
  liquidationProtocolFee: '1000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: true,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '2000000000',
  borrowCap: '0',
  debtCeiling: '0',
  borrowableIsolation: true,
};

export const strategyUSDC: IReserveParams = {
  strategy: rateStrategyUSDC,
  baseLTVAsCollateral: '7500',
  liquidationThreshold: '8000',
  liquidationBonus: '10500',
  liquidationProtocolFee: '1000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '6',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '1000000000',
  borrowCap: '800000000',
  debtCeiling: '0',
  borrowableIsolation: true,
};

export const strategyWETH: IReserveParams = {
  strategy: rateStrategyWETH,
  baseLTVAsCollateral: '7500',
  liquidationThreshold: '8000',
  liquidationBonus: '10500',
  liquidationProtocolFee: '1000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1500',
  supplyCap: '200000',
  borrowCap: '150000',
  debtCeiling: '0',
  borrowableIsolation: false,
};

export const strategyWstETH: IReserveParams = {
  strategy: rateStrategyWstETH,
  baseLTVAsCollateral: '7000',
  liquidationThreshold: '7500',
  liquidationBonus: '10700',
  liquidationProtocolFee: '2000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '2000',
  supplyCap: '200000',
  borrowCap: '150000',
  debtCeiling: '0',
  borrowableIsolation: false,
};

export const strategyWBTC: IReserveParams = {
  strategy: rateStrategyWBTC,
  baseLTVAsCollateral: '6000',
  liquidationThreshold: '6500',
  liquidationBonus: '10700',
  liquidationProtocolFee: '2000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '8',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '2000',
  supplyCap: '20000',
  borrowCap: '16000',
  debtCeiling: '0',
  borrowableIsolation: false,
};

export const strategyUSDT: IReserveParams = {
  strategy: rateStrategyUSDT,
  baseLTVAsCollateral: '7500',
  liquidationThreshold: '8000',
  liquidationBonus: '10500',
  liquidationProtocolFee: '1000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '6',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '2000000000',
  borrowCap: '1600000000',
  debtCeiling: '0',
  borrowableIsolation: true,
};

export const strategyHOPE: IReserveParams = {
  strategy: rateStrategyHOPE,
  baseLTVAsCollateral: '7000',
  liquidationThreshold: '7500',
  liquidationBonus: '11500',
  liquidationProtocolFee: '2000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '2000',
  supplyCap: '200000000',
  borrowCap: '160000000',
  debtCeiling: '0',
  borrowableIsolation: false,
};

export const strategyStakingHOPE: IReserveParams = {
  strategy: rateStrategyStakingHOPE,
  baseLTVAsCollateral: '6500',
  liquidationThreshold: '7000',
  liquidationBonus: '12000',
  liquidationProtocolFee: '2000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '2000',
  supplyCap: '100000000',
  borrowCap: '80000000',
  debtCeiling: '0',
  borrowableIsolation: false,
};
