import { eContractid, IReserveParams } from '../../helpers/types';

import {
  rateStrategyVolatileOne,
  rateStrategyStableOne,
  rateStrategyStableTwo,
  rateStrategyWETH,
  rateStrategyWstETH,
  rateStrategyHOPE,
  rateStrategyUSDT,
  rateStrategyWBTC,
  rateStrategyUSDC,
} from './rateStrategies';

export const strategyDAI: IReserveParams = {
  strategy: rateStrategyStableTwo,
  baseLTVAsCollateral: '7500',
  liquidationThreshold: '8000',
  liquidationBonus: '10500',
  liquidationProtocolFee: '1000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: true,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '2000000000',
  borrowCap: '0',
  debtCeiling: '0',
  borrowableIsolation: true,
};

export const strategyUSDC: IReserveParams = {
  strategy: rateStrategyUSDC,
  baseLTVAsCollateral: '7700',
  liquidationThreshold: '7900',
  liquidationBonus: '10450',
  liquidationProtocolFee: '2000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '6',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '1760000000',
  borrowCap: '1580000000',
  debtCeiling: '0',
  borrowableIsolation: true,
};

export const strategyWETH: IReserveParams = {
  strategy: rateStrategyWETH,
  baseLTVAsCollateral: '8050',
  liquidationThreshold: '8300',
  liquidationBonus: '10500',
  liquidationProtocolFee: '1000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1500',
  supplyCap: '1800000',
  borrowCap: '1400000',
  debtCeiling: '0',
  borrowableIsolation: false,
};

export const strategyWstETH: IReserveParams = {
  strategy: rateStrategyWstETH,
  baseLTVAsCollateral: '6500',
  liquidationThreshold: '7950',
  liquidationBonus: '10700',
  liquidationProtocolFee: '2000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '200000',
  borrowCap: '100000',
  debtCeiling: '0',
  borrowableIsolation: false,
};

export const strategyWBTC: IReserveParams = {
  strategy: rateStrategyWBTC,
  baseLTVAsCollateral: '6500',
  liquidationThreshold: '7800',
  liquidationBonus: '10550',
  liquidationProtocolFee: '1500',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '8',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '40000',
  borrowCap: '26000',
  debtCeiling: '0',
  borrowableIsolation: false,
};

export const strategyUSDT: IReserveParams = {
  strategy: rateStrategyUSDT,
  baseLTVAsCollateral: '5000',
  liquidationThreshold: '7000',
  liquidationBonus: '10500',
  liquidationProtocolFee: '2000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '6',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '20000000',
  borrowCap: '14000000',
  debtCeiling: '0',
  borrowableIsolation: true,
};

export const strategyHOPE: IReserveParams = {
  strategy: rateStrategyHOPE,
  baseLTVAsCollateral: '6500',
  liquidationThreshold: '8000',
  liquidationBonus: '10450',
  liquidationProtocolFee: '1000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '2000000000',
  borrowCap: '1880000000',
  debtCeiling: '0',
  borrowableIsolation: false,
};

export const strategyStakingHOPE: IReserveParams = {
  strategy: rateStrategyHOPE,
  baseLTVAsCollateral: '6500',
  liquidationThreshold: '8000',
  liquidationBonus: '10450',
  liquidationProtocolFee: '1000',
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: '18',
  hTokenImpl: eContractid.HToken,
  reserveFactor: '1000',
  supplyCap: '2000000000',
  borrowCap: '1880000000',
  debtCeiling: '0',
  borrowableIsolation: false,
};
